#import <AccountitAPI/AccountitAPICPACompanyAnalyticsDashboardResponse.h>

@implementation AccountitAPICPACompanyAnalyticsPeriod
@end

@implementation AccountitAPICPACompanyAnalyticsSummary
@end

@implementation AccountitAPICPACompanyAnalyticsDailyPoint
@end

@implementation AccountitAPICPACompanyAnalyticsJobItem
@end

@implementation AccountitAPICPACompanyAnalyticsDashboardResponse
@end
