import type { CommunityPost, CommunityAnswer } from "./community-types";

export const mockPosts: CommunityPost[] = [
  {
    id: "p1",
    boardType: "CPA_PREP",
    title: "CPA 1차 시험 과목별 공부 시간 비중 어떻게 잡으셨나요?",
    content:
      "안녕하세요! 올해 1차 처음 준비하는 수험생입니다.\n회계학, 세법, 경제학, 상법 중에서 과목별로 시간을 어느 정도 배분해서 공부하셨는지 궁금합니다.\n특히 회계학이 처음이라 감이 잘 안 잡혀서 선배님들의 조언 부탁드립니다!\n감사합니다.",
    status: "ANSWERED",
    tags: ["#1차시험", "#공부전략", "#시간관리", "#회계학"],
    authorName: "익명",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    viewCount: 342,
    commentCount: 8,
    likeCount: 12,
    isResolved: true,
    acceptedAnswerId: "a1",
  },
  {
    id: "p2",
    boardType: "CPA_PREP",
    title: "실무수습 기관은 어떻게 찾는 게 좋을까요?",
    content:
      "2차 합격 후 실무수습 기관 선택을 고민하고 있습니다. Big4와 중소 법인의 장단점이 궁금합니다. 어떤 기준으로 선택하셨나요?",
    status: "QUESTION",
    tags: ["#실무수습", "#인턴"],
    authorName: "익명",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    viewCount: 68,
    commentCount: 3,
    likeCount: 4,
    isResolved: false,
  },
  {
    id: "p3",
    boardType: "CPA_PREP",
    title: "Big4 인턴 경험이 꼭 필요한가요?",
    content:
      "현재 대학교 3학년인데, Big4 인턴 경험이 없으면 취업에 불리한지 궁금합니다. 인턴 없이 합격하신 분 계신가요?",
    status: "QUESTION",
    tags: ["#Big4", "#인턴"],
    authorName: "익명",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    viewCount: 142,
    commentCount: 15,
    likeCount: 7,
    isResolved: false,
  },
  {
    id: "p4",
    boardType: "CPA_PREP",
    title: "2차 시험 선택과목 추천 부탁드립니다.",
    content:
      "재무관리와 원가관리회계 중 어느 과목이 더 합격하기 쉬운지 선배님들의 조언 부탁드립니다.",
    status: "QUESTION",
    tags: ["#2차시험", "#선택과목"],
    authorName: "익명",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    viewCount: 86,
    commentCount: 7,
    likeCount: 5,
    isResolved: false,
  },
  {
    id: "p5",
    boardType: "CPA_PREP",
    title: "비공자도 회계사 준비 가능한가요?",
    content:
      "타전공 출신인데 회계사 시험을 준비하고 싶습니다. 어떻게 시작하면 좋을까요?",
    status: "QUESTION",
    tags: ["#비전공", "#준비기간"],
    authorName: "익명",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    viewCount: 91,
    commentCount: 9,
    likeCount: 6,
    isResolved: false,
  },
  {
    id: "p6",
    boardType: "CPA_PREP",
    title: "재무관리 계산 문제 연습 방법 추천해주세요!",
    content:
      "재무관리 계산 문제가 너무 어렵습니다. 효과적인 연습 방법이 있을까요?",
    status: "QUESTION",
    tags: ["#재무관리", "#계산문제"],
    authorName: "익명",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    viewCount: 41,
    commentCount: 3,
    likeCount: 2,
    isResolved: false,
  },
  {
    id: "p7",
    boardType: "TRAINEE",
    title: "수습 첫 달 야근이 이렇게 많은 게 정상인가요?",
    content:
      "Big4 입사 후 첫 달인데 매일 12시까지 야근하고 있어요. 감사시즌이라 그런 건지 원래 이런 건지 궁금합니다.",
    status: "QUESTION",
    tags: ["#야근", "#수습생활"],
    authorName: "익명",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    viewCount: 213,
    commentCount: 14,
    likeCount: 20,
    isResolved: false,
  },
  {
    id: "p8",
    boardType: "TRAINEE",
    title: "팀 배치 지원은 어떻게 하나요?",
    content:
      "수습 3개월 차인데 감사팀 외에 세무팀도 가능한지, 팀 배치 지원 방식이 궁금합니다.",
    status: "ANSWERED",
    tags: ["#팀배치", "#수습생활"],
    authorName: "익명",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    viewCount: 87,
    commentCount: 6,
    likeCount: 9,
    isResolved: true,
    acceptedAnswerId: "a8",
  },
  {
    id: "p9",
    boardType: "TRAINEE",
    title: "감사보고서 작성 기초 어떻게 배우셨나요?",
    content:
      "신입 수습인데 감사보고서 작성이 막막합니다. 어떻게 공부하셨나요?",
    status: "QUESTION",
    tags: ["#감사업무", "#수습생활"],
    authorName: "익명",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    viewCount: 55,
    commentCount: 4,
    likeCount: 3,
    isResolved: false,
  },
  {
    id: "p10",
    boardType: "SENIOR",
    title: "Big4 3년차 → 인하우스 이직 고민",
    content:
      "현재 Big4 3년차인데 인하우스로 이직을 고민하고 있습니다. 연봉이나 커리어 측면에서 어떻게 생각하시나요?",
    status: "QUESTION",
    tags: ["#이직", "#인하우스", "#커리어패스"],
    authorName: "익명",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    viewCount: 456,
    commentCount: 22,
    likeCount: 34,
    isResolved: false,
  },
  {
    id: "p11",
    boardType: "SENIOR",
    title: "FAS vs Deal 어느 쪽이 커리어에 유리한가요?",
    content:
      "5년차 회계사인데 FAS와 Deal 부서 이동을 고민하고 있습니다. 장기적으로 어느 쪽이 유리할까요?",
    status: "ANSWERED",
    tags: ["#FAS", "#Deal", "#커리어패스"],
    authorName: "익명",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    viewCount: 312,
    commentCount: 11,
    likeCount: 18,
    isResolved: true,
    acceptedAnswerId: "a11",
  },
  {
    id: "p12",
    boardType: "SENIOR",
    title: "연봉 협상 시 참고할 수 있는 기준이 있나요?",
    content:
      "이직 협상 때 연봉 기준을 어떻게 잡으셨는지 경험 공유해 주세요.",
    status: "QUESTION",
    tags: ["#연봉", "#이직"],
    authorName: "익명",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    viewCount: 189,
    commentCount: 8,
    likeCount: 22,
    isResolved: false,
  },
  {
    id: "p13",
    boardType: "FREE",
    title: "2025년 CPA 시험 일정 정리 (1차/2차)",
    content:
      "2025년 CPA 1차, 2차 시험 일정을 정리했습니다. 참고하세요!\n\n1차: 2025년 2월 22일(토)\n2차: 2025년 6월 28-29일(토-일)",
    status: "INFO",
    tags: ["#정보공유"],
    authorName: "익명",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    viewCount: 203,
    commentCount: 2,
    likeCount: 45,
    isResolved: false,
  },
  {
    id: "p14",
    boardType: "FREE",
    title: "회계사 시험 공부하면서 체력 관리하는 법",
    content:
      "수험생활 2년 동안 체력 관리하는 방법을 공유합니다. 규칙적인 수면이 가장 중요했어요.",
    status: "FREE",
    tags: ["#잡담", "#회계사생활"],
    authorName: "익명",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    viewCount: 98,
    commentCount: 5,
    likeCount: 12,
    isResolved: false,
  },
  {
    id: "p15",
    boardType: "FREE",
    title: "Big4 합격 후기 공유합니다",
    content:
      "올해 Big4 최종 합격했습니다! 준비 과정과 면접 팁을 공유합니다.",
    status: "INFO",
    tags: ["#후기", "#Big4"],
    authorName: "익명",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    viewCount: 445,
    commentCount: 18,
    likeCount: 67,
    isResolved: false,
  },
];

export const mockAnswers: CommunityAnswer[] = [
  {
    id: "a1",
    postId: "p1",
    content:
      "저는 회계학 40%, 세법 30%, 경제학 20%, 상법 10% 비중으로 계획했어요.\n회계학은 기본기가 가장 중요해서 처음엔 시간을 더 많이 투자했고,\n세법은 암기량이 많아서 꾸준히 반복하는 태 집중했습니다.\n경제학은 문제들이 위주로, 상법은 조문 위주로 학습했어요.\n본인 상황에 맞게 조정하시면 좋을 것 같습니다!",
    authorName: "익명(선배CPA)",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    likeCount: 25,
    isAccepted: true,
  },
  {
    id: "a1b",
    postId: "p1",
    content:
      "저도 회계학이 제일 오래 걸리더라구요ㅠㅠ\n저는 회계학 50%까지도 가져갔습니다. 나머지는 비슷하게 했어요.",
    authorName: "익명(수험생)",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    likeCount: 7,
    isAccepted: false,
  },
  {
    id: "a8",
    postId: "p8",
    content:
      "법인마다 다르지만 보통 수습 6개월 후 팀 배치 지원서를 제출합니다. HR에 문의해보시면 정확한 일정 알려줄 거예요.",
    authorName: "익명(3년차)",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    likeCount: 12,
    isAccepted: true,
  },
  {
    id: "a11",
    postId: "p11",
    content:
      "장기적으로는 Deal 쪽이 M&A 쪽으로 커리어 확장이 더 유리합니다. FAS는 다양한 경험을 할 수 있고요. 본인이 어떤 방향을 원하는지에 따라 다릅니다.",
    authorName: "익명(파트너)",
    isAnonymous: true,
    createdAt: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
    likeCount: 30,
    isAccepted: true,
  },
];
